# Customization for Newcastle University's Comet Cluster
# Use the HPC_CARPENTRY_CUSTOMIZATION variable to invoke these:
#
# > HPC_CARPENTRY_CUSTOMIZATION=episodes/files/customization/NCL_Comet_slurm/_config_options.yml
# > export HPC_CARPENTRY_CUSTOMIZATION
---
snippets: episodes/files/customization/Plato_slurm/snippets/

local:
  prompt: "[you@laptop:~]$"
  shebang: "#!/usr/bin/env bash"

remote:
  name: "Plato"
  host_id: "FIXME_Plato"
  login: "plato.usask.ca"
  host: "platolgn001"
  node: "platocpu028"
  location: "plato.usask.ca"
  user: "abc123"
  prompt: '[abc123@platolgn001 ~]'
  shebang: "#!/bin/bash"

  fs:
    home: "/home"

  module_python3:
    python: "N/A"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--account=hpc_s_workshop"
  queue:
    debug: "N/A"
    testing: "short_free"
  reservation: "shortqos"
  qos: "short"
  account: "comet_training"
  project: "FIXME_comet_training"
  comment: '#'
  flag:
    name: "#SBATCH"